---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - config/telegram_config.yml

  tasks:

  - uri: url="https://api.telegram.org/{{ tokenBot }}/sendmessage?chat_id={{ chatID }}&parse_mode=HTML&text=<b>You%20have%20new%20pending%20approvals.</b>%20Check%20Ansible%20Tower"
